version: "3"
 
services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
      args:
        IMAGE_NAME: "ritika93046/nasa-mission:latest"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo_db:27017/nasa-mission
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/node_modules
 
      
  jenkins:
    build:
      context: .
      dockerfile: DockerfileJenkins
    hostname: jenkins
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube/config:/root/.kube/config
      - ~/.minikube:/root/.minikube
    
volumes:
  jenkins-data:
 