name: NASA Project CI
on : 
 push: 
  branches: [ main ]
jobs:
 build:
  env:
    CI: true
    MONGO_URL: mongodb://localhost/nasa
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Use node version 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Use MongoDb for github actions/checkout
      uses: supercharge/mongodb-github-action@1.10.0
    - run: npm install
    - run: npm run build --prefix client
    - run: npm run test